server:
  port: 8085

spring:
  application:
    name:
      statistics-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: statistics_service_db

  liquibase:
    enabled: true
    default_schema: statistics_service_db

security:
  internal:
    token: Iq6Vu8Nz7Xa3Rl9Cm5YbTc2WpDf4Oj5ZfGn1Kh3

integration:
  rabbit:
    user-service:
      user-queue: user-stats-queue
  rest:
    user-service-url: http://localhost:8080
