spring:
  application:
    name: statistics-service
  profiles:
    active: local

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: "/v1/internal/actuator"