spring:
  application:
    name:
      statistics-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/statistics-service-test-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true