server:
  port: 8085

spring:
  application:
    name: statistics-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: statistics_service_db
  liquibase:
    enabled: true
    default_schema: statistics_service_db

security:
  internal:
    token: YzNSaGRHbHpkR2xqY3kxcGJuUmxjbTVoYkMxclpYaz0K

integration:
  rabbit:
    inbound:
      user-service:
        queue: user-stats-queue
  rest:
    auth-service-url: http://localhost:8081
    services:
      user:
        url: http://localhost:8080
        token: ZFhObGNsTmxjblpwWTJVdGFXNTBaWEp1WVd3dGEyVjU=

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://103.249.132.74:9411/api/v2/spans